package com.kama.mindagent.agent;

enum AgentFailureCode {
    AGENT_PROTOCOL_ERROR,
    MODEL_CALL_FAILED,
    TOOL_EXECUTION_FAILED,
    FINAL_ANSWER_MISSING,
    MAX_STEPS_EXCEEDED,
    PLAN_REQUIRED,
    PLAN_DISABLED,
    PLAN_PROTOCOL_ERROR,
    MAX_PLAN_REVISIONS_EXCEEDED,
    MAX_MODEL_CALLS_EXCEEDED,
    MAX_TOOL_CALLS_EXCEEDED,
    MAX_RUN_DURATION_EXCEEDED
}
